#!/usr/bin/env python3
"""Generate src/tokens.css from design/tokens.json.

tokens.json is the source of token values, edited by hand (docs/design/tokens.md);
this script is the only thing that writes tokens.css. Run `just gen packages/ui`.
`just check` regenerates into memory and fails if the committed CSS differs.

Nothing here infers a unit or a type: both are explicit per token in tokens.json,
because inference is how an opacity token ends up emitted as `0.5px`.
"""
import json, pathlib, sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from tokens_schema import SUPPORTED_AXES, validate  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent

# device axis value -> the width range it owns, in CSS px. Compact is the
# mobile-first base and so has no query. Ranges are contiguous: each `min` is the
# previous range's exclusive upper bound, so no width falls between two regimes.
DEVICE_MIN = {"medium": 768, "wide": 1200, "ultra": 1800}

def render(name, spec, value):
    unit = spec.get("unit")
    kind = spec["type"]
    if kind == "color":
        return value
    if kind == "fontFamily":
        fallback = ("ui-monospace, SFMono-Regular, monospace" if "mono" in name
                    else "system-ui, -apple-system, Segoe UI, sans-serif")
        return f'"{value}", {fallback}'
    if kind == "cubicBezier":
        return value
    if unit is None:
        return str(value)
    if value == 0 and unit == "px":
        return "0"
    return f"{value}{unit}"


def decls(tokens, pick, indent="  "):
    out = []
    for name, spec in tokens.items():
        v = pick(name, spec)
        if v is None:
            continue
        out.append(f"{indent}--{name}: {render(name, spec, v)};")
    return out


def build(doc):
    t = doc["tokens"]
    L, add = [], None
    L = []
    add = L.append
    add("/* GENERATED by scripts/gen-tokens.py from design/tokens.json. Do not edit. */")
    add("")
    add("/* Base: light, device=compact (mobile first), density=comfortable. */")
    add(":root {")
    L += decls(t, lambda n, s: s.get("default",
               s.get("color", {}).get("light",
               s.get("device", {}).get("compact",
               s.get("density", {}).get("comfortable")))))
    add("  color-scheme: light;")
    add("}")
    add("")
    dark = decls(t, lambda n, s: s.get("color", {}).get("dark"), "    ")
    add("/* The viewer's setting, unless the page pins a theme. color-scheme is set")
    add("   alongside the custom properties: without it, native controls, form")
    add("   widgets and scrollbars keep the OS appearance and contradict the page. */")
    add("@media (prefers-color-scheme: dark) {")
    add("  :root:not([data-theme=\"light\"]) {")
    L += dark
    add("    color-scheme: dark;")
    add("  }")
    add("}")
    add("")
    add("/* An explicit choice wins in both directions, and carries color-scheme with it. */")
    add(":root[data-theme=\"dark\"] {")
    L += [d[2:] for d in dark]
    add("  color-scheme: dark;")
    add("}")
    add("")
    add(":root[data-theme=\"light\"] {")
    L += decls(t, lambda n, s: s.get("color", {}).get("light"))
    add("  color-scheme: light;")
    add("}")
    add("")
    add("/* device axis. Resolves from the viewport. */")
    for value, minw in DEVICE_MIN.items():
        rows = decls(t, lambda n, s, v=value: s.get("device", {}).get(v), "    ")
        if not rows:
            continue
        add(f"@media (min-width: {minw}px) {{")
        add("  :root {")
        L += rows
        add("  }")
        add("}")
        add("")
    add("/* density axis. Both values are emitted so a comfortable subtree nested")
    add("   inside a compact one resolves correctly — with only the compact rule,")
    add("   the inner subtree would inherit compact values it never asked for. */")
    for value in ("comfortable", "compact"):
        rows = decls(t, lambda n, s, v=value: s.get("density", {}).get(v))
        if not rows:
            continue
        add(f"[data-density=\"{value}\"] {{")
        L += rows
        add("}")
        add("")
    add("/* Reduced motion. The durations collapse; the easing tokens are left alone")
    add("   because a curve with no time to run is harmless, and keeping them means")
    add("   a component need not branch. Nothing is removed and no state becomes")
    add("   unreachable — a drawer still opens, it simply is open. */")
    add("@media (prefers-reduced-motion: reduce) {")
    add("  :root {")
    for name, spec in t.items():
        if spec["type"] == "duration":
            L.append(f"    --{name}: 0ms;")
    add("  }")
    add("}")
    add("")
    add("/* Touch floor. Keyed to pointer capability, not width: a large tablet is")
    add("   a wide viewport with coarse input, and a narrow desktop window is the")
    add("   reverse. Layout regimes stay width-driven; the target floor does not. */")
    add("@media (any-pointer: coarse) {")
    add("  [data-density=\"compact\"] {")
    L += decls(t, lambda n, s: s.get("density", {}).get("comfortable"), "    ")
    add("  }")
    add("}")
    return "\n".join(L) + "\n"


def main():
    doc = json.loads((ROOT / "design/tokens.json").read_text())
    problems = validate(doc)
    if problems:
        # Refuse to write. Generating from an invalid document overwrites a good
        # stylesheet with a bad one and exits 0, so the damage outlives the run.
        for p in problems:
            print("INVALID " + p, file=sys.stderr)
        print(f"{len(problems)} problem(s) in design/tokens.json — nothing written",
              file=sys.stderr)
        return 1
    css = build(doc)
    out = ROOT / "src/tokens.css"
    if "--check" in sys.argv:
        if not out.exists() or out.read_text() != css:
            print("tokens.css is stale — run `just gen packages/ui`", file=sys.stderr)
            return 1
        print(f"tokens.css matches tokens.json ({len(doc['tokens'])} tokens)")
        return 0
    out.write_text(css)
    print(f"wrote {out} ({len(doc['tokens'])} tokens)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
