#!/usr/bin/env python3
"""Generate src/tokens.css from design/tokens.json.

tokens.json is exported from the pen.dev library by hand (see docs/design/tokens.md);
this script is the only thing that writes tokens.css. Run `just gen packages/ui`.
`just check` re-runs it into memory and fails if the committed CSS differs.
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
UNITLESS = {"type-line-normal", "type-line-table", "type-line-tight"}
MS = {"motion-duration-base", "motion-duration-fast", "motion-duration-slow"}
RAW = {"string"}
# device axis value -> min-width in CSS px. Compact is the mobile-first base.
DEVICE_MIN = {"medium": 768, "wide": 1200, "ultra": 1800}


def fmt(name, spec, value):
    if spec["type"] == "color":
        return value
    if spec["type"] == "string":
        if name.startswith("type-family"):
            fallback = "ui-monospace, SFMono-Regular, monospace" if "mono" in name \
                else "system-ui, -apple-system, Segoe UI, sans-serif"
            return f'"{value}", {fallback}'
        return value
    if name in UNITLESS:
        return str(value)
    if name in MS:
        return f"{value}ms"
    return "0" if value == 0 else f"{value}px"


def decls(tokens, pick, indent="  "):
    out = []
    for name, spec in tokens.items():
        v = pick(name, spec)
        if v is None:
            continue
        out.append(f"{indent}--{name}: {fmt(name, spec, v)};")
    return out


def build(doc):
    t = doc["tokens"]
    L = []
    add = L.append
    add("/* GENERATED by scripts/gen-tokens.py from design/tokens.json. Do not edit. */")
    add("")
    add("/* Base: light, device=compact (mobile first), density=comfortable. */")
    add(":root {")
    L += decls(t, lambda n, s: s.get("default",
               s.get("color", {}).get("light",
               s.get("device", {}).get("compact",
               s.get("density", {}).get("comfortable")))))
    add("  color-scheme: light dark;")
    add("}")
    add("")
    dark = decls(t, lambda n, s: s.get("color", {}).get("dark"), "    ")
    add("/* The viewer's setting, unless the page pins a theme. */")
    add("@media (prefers-color-scheme: dark) {")
    add("  :root:not([data-theme=\"light\"]) {")
    L += dark
    add("  }")
    add("}")
    add("")
    add("/* An explicit choice always wins, in both directions. */")
    add(":root[data-theme=\"dark\"] {")
    L += [d[2:] for d in dark]
    add("}")
    add("")
    add("/* device axis. Unlike the canvas, this resolves from the viewport. */")
    for value, minw in DEVICE_MIN.items():
        rows = decls(t, lambda n, s, v=value: s.get("device", {}).get(v), "    ")
        if not rows:
            continue
        add(f"@media (min-width: {minw}px) {{")
        add("  :root {")
        L += rows
        add("  }")
        add("}")
        add("")
    add("/* density axis. Opt in per subtree. */")
    add("[data-density=\"compact\"] {")
    L += decls(t, lambda n, s: s.get("density", {}).get("compact"))
    add("}")
    add("")
    add("/* density=compact is never honoured on touch: a 40px row is a poor thumb")
    add("   target, so below the compact breakpoint it reverts to comfortable. */")
    add("@media (max-width: 767px) {")
    add("  [data-density=\"compact\"] {")
    L += decls(t, lambda n, s: s.get("density", {}).get("comfortable"), "    ")
    add("  }")
    add("}")
    return "\n".join(L) + "\n"


def main():
    doc = json.loads((ROOT / "design/tokens.json").read_text())
    css = build(doc)
    out = ROOT / "src/tokens.css"
    if "--check" in sys.argv:
        if not out.exists() or out.read_text() != css:
            print("tokens.css is stale — run `just gen packages/ui`", file=sys.stderr)
            return 1
        print(f"tokens.css matches tokens.json ({len(doc['tokens'])} tokens)")
        return 0
    out.write_text(css)
    print(f"wrote {out} ({len(doc['tokens'])} tokens)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
