// The banking contract's public surface. gen/ is generated and never edited;
// this file is what other packages import.
export {
	BankingService,
	Level,
	AccountSource,
	Failure,
	type Bank,
	type Member,
	type Money,
	type Balance,
	type Account,
	type Connection,
	type CurrencyTotal,
	type BankFailure,
	type AccountGrant,
	type ListBanksRequest,
	type ListBanksResponse,
	type BeginConnectionRequest,
	type BeginConnectionResponse,
	type CompleteConnectionRequest,
	type CompleteConnectionResponse,
	type ListConnectionAccountsRequest,
	type ListConnectionAccountsResponse,
	type SetAccountOwnersRequest,
	type SetAccountOwnersResponse,
	type SetAccountLevelRequest,
	type SetAccountLevelResponse,
	type ListAccountsRequest,
	type ListAccountsResponse,
	type RefreshBalancesRequest,
	type RefreshBalancesResponse,
	type RestoreConnectionRequest,
	type RestoreConnectionResponse,
	type DisconnectBankRequest,
	type DisconnectBankResponse
} from '../gen/ts/wimm/banking/v1/banking_pb.js';
